[2024-05-10T10:00:14.435+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T09:40:00+00:00 map_index=13 [queued]>
[2024-05-10T10:00:14.545+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T09:40:00+00:00 map_index=13 [queued]>
[2024-05-10T10:00:14.545+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-05-10T10:00:14.675+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-10 09:40:00+00:00
[2024-05-10T10:00:14.721+0000] {standard_task_runner.py:60} INFO - Started process 911192 to run task
[2024-05-10T10:00:14.779+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-10T09:40:00+00:00', '--job-id', '47336', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpfroijdcl', '--map-index', '13']
[2024-05-10T10:00:14.801+0000] {standard_task_runner.py:88} INFO - Job 47336: Subtask ETL_job
[2024-05-10T10:00:15.064+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T09:40:00+00:00 map_index=13 [running]> on host a09da322e808
[2024-05-10T10:00:15.505+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T09:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T09:40:00+00:00'
[2024-05-10T10:00:15.506+0000] {Units_dag.py:98} INFO - i: 130000, chunk: 10000
[2024-05-10T10:00:15.506+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1MzM1MjA0LCJleHAiOjE3MTc5MjcyMDQsIm5iZiI6MTcxNTMzNTIwNCwianRpIjoicXhsT3F5dTMwZERSZW1MeiIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.BCuAsvx2I8-RwZBZvKgNvHiooXdbpAbTt3ZrygknFqQ
[2024-05-10T10:00:36.534+0000] {Units_dag.py:103} INFO - {'_id': '651174417a353511ea42258d', 'icon': 'icons/icon.png', 'driver_id': '6579609528a4976ce50c747e', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'shipment_info': {'product_category': None, 'truck_type': None, 'shipment_type': None, 'shipment_payment_type': None, 'transporter_type': None, 'operating_area': None, 'weight_kilograms_per_day': None, 'kms_per_day': None, 'shipment_trip_drive_hrs_day': None, 'allowable_delay_drive_hrs_day': None, 'expected_shipment_trip_day': None, 'car_pay_per_day': None, 'exceeding_temperature_limit_per_day': None, 'temperature_upper_limit': None, 'exceeding_humidity_limit_per_day': None, 'humidity_upper_limit': None}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'name': '7834 T G A', 'operation_code': '', 'device_gateway': '', 'skip_sim_information': False, 'imei': '863719060655736', 'sim_number': '+966830032219875', 'sim_serial': '8996609821111926781', 'device_serial': '1131866403', 'device': 'teltonika', 'user_id': '64d8c62c2d774b6f343b34f7', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2023-09-25 14:51:29', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'cap-france-bat-saudi-admin', 'last_update': {'dtt': 1715334965000, 'dts': 1715334968070, 'spd': 0, 'ang': 223, 'alt': 658, 'chPrams': {'pdop': {'v': 0.8, 'cdt': 1715334664000}, 'Speed': {'v': 0, 'cdt': 1715164948000}, 'output1': {'v': False, 'cdt': 1715133667000}, 'rssi': {'v': 5, 'cdt': 1715144234000}, 'workMode': {'v': 0, 'cdt': 1715223469000}, 'ePwrV': {'v': 12.870000000000001, 'cdt': 1715334364000}, 'parm24': {'v': 0, 'cdt': 1715164948000}, 'sat': {'v': 19, 'cdt': 1715334664000}, 'type': {'v': 6, 'cdt': 1714294519000}, 'priority': {'v': 0, 'cdt': 1715165880000}, 'di1': {'v': 0, 'cdt': 1715223139000}, 'hdop': {'v': 0.5, 'cdt': 1715334364000}, 'result': {'v': '5665723a30332e32372e31345f3030204750533a41584e5f352e312e392048773a464d43313330204d6f643a3420494d45493a38363337313930363036353537333620496e69743a323032342d352d3420363a353020557074696d653a333338323336204d41433a373144304532464136323631205350433a312830292041584c3a32204f42443a3020424c3a312e31302042543a34', 'cdt': 1715144216000}, 'protocol': {'v': 'FMC130', 'cdt': 1715133667000}, 'gpsStatus': {'v': 1, 'cdt': 1715069695000}, 'iPwrV': {'v': 4.043, 'cdt': 1715334364000}, 'event': {'v': 0, 'cdt': 1715165880000}}, 'prms': {'protocol': 'FMC130', 'priority': 0, 'sat': 19, 'event': 0, 'di1': 0, 'workMode': 0, 'rssi': 5, 'gpsStatus': 1, 'output1': 0, 'pdop': 0.8, 'hdop': 0.5, 'ePwrV': 12.870000000000001, 'Speed': 0, 'parm24': 0, 'iPwrV': 4.043}, 'devPrms': ['protocol', 'priority', 'sat', 'event', 'di1', 'workMode', 'rssi', 'gpsStatus', 'output1', 'pdop', 'hdop', 'ePwrV', 'Speed', 'parm24', 'iPwrV'], 'old_params': {'pdop': 0.8, 'Speed': 0, 'rssi': 5, 'output1': 0, 'workMode': 0, 'ePwrV': 12.870000000000001, 'parm24': 0, 'sat': 19, 'priority': 0, 'di1': 0, 'hdop': 0.5, 'protocol': 'teltonika', 'gpsStatus': 1, 'iPwrV': 4.043, 'event': 0}, 'vLoc': 1, 'vCon': 1, 'ip': '109.83.202.180', 'rl': 0, 'trl': 10314.4819, 'mdu': 0, 'tmdu': 807945, 'eidl': 0, 'teidl': 543123, 'fc': 0, 'tfc': 519.384114, 'acc': 0, 'accOn': 2355458, 'accOff': 638533302, 'sdu': 301, 'tsdu': 111826, 'lat': 24.77988, 'lng': 46.7064383}, 'counters': {'odometer_type': '', 'odometer': 10313.6573, 'engine_hours_type': '', 'engine_hours': 2355458, 'last_acc': 0}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-10T10:00:37.852+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T10:00:38.012+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T10:00:38.181+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T10:00:38.219+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T10:00:38.287+0000] {_transport.py:335} INFO - GET https://dbelk1.afaqy.local:9200/_cluster/health [status:200 duration:0.105s]
[2024-05-10T10:00:39.605+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T10:00:41.391+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:1.891s]
[2024-05-10T10:00:42.209+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 1628 document(s) failed to index.
[2024-05-10T10:00:42.524+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=13, execution_date=20240510T094000, start_date=20240510T100014, end_date=20240510T100042
[2024-05-10T10:00:43.584+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 47336 for task ETL_job (1628 document(s) failed to index.; 911192)
[2024-05-10T10:00:43.755+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-10T10:00:43.811+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
