[2024-04-16T07:16:43.563+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-16T06:00:00+00:00 map_index=9 [queued]>
[2024-04-16T07:16:43.574+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-16T06:00:00+00:00 map_index=9 [queued]>
[2024-04-16T07:16:43.575+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-04-16T07:16:43.594+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-16 06:00:00+00:00
[2024-04-16T07:16:43.601+0000] {standard_task_runner.py:60} INFO - Started process 326977 to run task
[2024-04-16T07:16:43.623+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-04-16T06:00:00+00:00', '--job-id', '3851', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp9vwyz1zk', '--map-index', '9']
[2024-04-16T07:16:43.630+0000] {standard_task_runner.py:88} INFO - Job 3851: Subtask ETL_job
[2024-04-16T07:16:43.784+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-16T06:00:00+00:00 map_index=9 [running]> on host a09da322e808
[2024-04-16T07:16:43.983+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T06:00:00+00:00'
[2024-04-16T07:16:43.985+0000] {Units_dag.py:90} INFO - i: 90000, chunk: 10000
[2024-04-16T07:16:43.985+0000] {Units_dag.py:91} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzEzMjUwODA0LCJleHAiOjE3MTU4NDI4MDQsIm5iZiI6MTcxMzI1MDgwNCwianRpIjoieTE3aXZmQUFyR3JQU0pqcSIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.gsyLu_Gx11ieWmkPFJYogPd_Xw96CzvfJa5zCnVkARE
[2024-04-16T07:17:03.401+0000] {Units_dag.py:95} INFO - {'_id': '64088a494d067a282c0c1784', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'measurement_type': 'count', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '7738 ر ر ح', 'operation_code': None, 'device_gateway': None, 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '861937062950242', 'sim_number': '+966830031781613', 'sim_serial': '21296721868', 'device_serial': '861937062950242', 'device': 'bce', 'user_id': '5f8bf21303ed52b7fb1c11ba', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2023-12-31 12:08:25', 'created_at': '2023-03-08 16:14:49', 'creator': 'amr.ahmed', 'company': '', 'owner': 'alwefaq-rent', 'last_update': {'dtt': 1713251624000, 'dts': 1713251683791, 'spd': 0, 'ang': 44, 'alt': 65533, 'chPrams': {'ePwrV': {'v': 12.564, 'cdt': 1713251144000}, 'di16': {'v': 1, 'cdt': 1712939364000}, 'rssi1': {'v': 60, 'cdt': 1713251504000}, 'di15': {'v': 0, 'cdt': 1712939364000}, 'di14': {'v': 0, 'cdt': 1713240248000}, 'di13': {'v': 0, 'cdt': 1712939364000}, 'di12': {'v': 0, 'cdt': 1712939364000}, 'di11': {'v': 0, 'cdt': 1712939364000}, 'di10': {'v': 0, 'cdt': 1712939364000}, 'di2': {'v': 0, 'cdt': 1712939364000}, 'di1': {'v': 0, 'cdt': 1713240526000}, 'ai4': {'v': 196, 'cdt': 1713251084000}, 'di4': {'v': 0, 'cdt': 1712939364000}, 'di3': {'v': 0, 'cdt': 1712939364000}, 'di6': {'v': 0, 'cdt': 1712939364000}, 'di5': {'v': 0, 'cdt': 1713240526000}, 'lac1': {'v': 12111, 'cdt': 1713239996000}, 'protocol': {'v': 'bce', 'cdt': 1712939364000}, 'di8': {'v': 1, 'cdt': 1712939364000}, 'di7': {'v': 0, 'cdt': 1713240496000}, 'di9': {'v': 0, 'cdt': 1712939364000}, 'iPwrV': {'v': 3.96, 'cdt': 1713251084000}, 'humidity': {'v': -1, 'cdt': 1712939364000}, 'ID': {'v': '0', 'cdt': 1712939364000}, 'cid1': {'v': 12203, 'cdt': 1713240452000}, 'temp': {'v': -273, 'cdt': 1712939364000}, 'odometer': {'v': 0, 'cdt': 1713240502000}, 'spd': {'v': 0, 'cdt': 1713240506000}, 'sat': {'v': 12, 'cdt': 1713220210000}, 'hdop': {'v': 1, 'cdt': 1712568074000}, 'ta': {'v': 0, 'cdt': 1712939364000}, 'mcc1': {'v': 420, 'cdt': 1713223150000}, 'mnc1': {'v': 4, 'cdt': 1713211930000}}, 'prms': {'protocol': 'bce', 'spd': 0, 'sat': 12, 'hdop': 1, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 0, 'di6': 0, 'di5': 0, 'di4': 0, 'di3': 0, 'di2': 0, 'di1': 0, 'ePwrV': 12.564, 'ai4': 196, 'iPwrV': 3.96, 'ta': 0, 'mcc1': 420, 'mnc1': 4, 'lac1': 12111, 'cid1': 12203, 'rssi1': 60, 'ID': '0', 'temp': -273, 'humidity': -1}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'ai4', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1', 'ID', 'temp', 'humidity'], 'old_params': {'protocol': 'bce', 'spd': 0, 'sat': 12, 'hdop': 1, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 0, 'di6': 0, 'di5': 0, 'di4': 0, 'di3': 0, 'di2': 0, 'di1': 0, 'ePwrV': 12.564, 'ai4': 196, 'iPwrV': 3.96, 'ta': 0, 'mcc1': 420, 'mnc1': 4, 'lac1': 12111, 'cid1': 12203, 'rssi1': 60, 'ID': '0', 'temp': -273, 'humidity': -1}, 'vLoc': 1, 'vCon': 1, 'ip': '51.36.15.135', 'rl': 0, 'trl': 20146.2452, 'mdu': 0, 'tmdu': 902794, 'eidl': 0, 'teidl': 145510, 'fc': 0, 'tfc': 65.36436, 'acc': 0, 'accOn': 3375956, 'accOff': 15065126, 'sdu': 60, 'tsdu': 11098, 'lat': 27.0610408782959, 'lng': 49.5319938659668}, 'counters': {'odometer_type': 'gps', 'odometer': 47633.4697, 'engine_hours_type': 'acc', 'engine_hours': 3375956, 'last_acc': 0}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-04-16T07:17:03.787+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-16T07:17:03.820+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-16T07:17:03.852+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-16T07:17:04.745+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-16T07:17:04.841+0000] {_transport.py:335} INFO - GET https://dbelk2.afaqy.local:9200/_cluster/health [status:200 duration:0.987s]
[2024-04-16T07:17:05.232+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-16T07:17:05.498+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.296s]
[2024-04-16T07:17:05.735+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 103, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-04-16T07:17:05.746+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=9, execution_date=20240416T060000, start_date=20240416T071643, end_date=20240416T071705
[2024-04-16T07:17:05.765+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3851 for task ETL_job (10000 document(s) failed to index.; 326977)
[2024-04-16T07:17:05.828+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-16T07:17:05.862+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
