[2024-04-29T06:01:54.339+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-29T05:40:00+00:00 map_index=9 [queued]>
[2024-04-29T06:01:54.378+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-29T05:40:00+00:00 map_index=9 [queued]>
[2024-04-29T06:01:54.378+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 4
[2024-04-29T06:01:54.440+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-29 05:40:00+00:00
[2024-04-29T06:01:54.464+0000] {standard_task_runner.py:60} INFO - Started process 631811 to run task
[2024-04-29T06:01:54.495+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-04-29T05:40:00+00:00', '--job-id', '22485', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp_aw6t87z', '--map-index', '9']
[2024-04-29T06:01:54.497+0000] {standard_task_runner.py:88} INFO - Job 22485: Subtask ETL_job
[2024-04-29T06:01:54.652+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-29T05:40:00+00:00 map_index=9 [running]> on host a09da322e808
[2024-04-29T06:01:55.020+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T05:40:00+00:00'
[2024-04-29T06:01:55.021+0000] {Units_dag.py:99} INFO - i: 90000, chunk: 10000
[2024-04-29T06:01:55.022+0000] {Units_dag.py:100} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE0MzcwNDAzLCJleHAiOjE3MTY5NjI0MDMsIm5iZiI6MTcxNDM3MDQwMywianRpIjoiZWRaOFQ3bE8wQ3IxM2tESSIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.fO9a0u19FIYz4jXUeoccFPd188YOyZ2Sd7nuGgBy9ac
[2024-04-29T06:02:16.345+0000] {Units_dag.py:104} INFO - {'_id': '640d6e2d882d71355b0ee107', 'icon': 'icons/icon.png', 'driver_id': '646db7fb104c9542e45dc804', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '1583 - E S A', 'operation_code': '', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': False, 'water': False}, 'imei': '354017119555650', 'sim_number': '+966830032369206', 'sim_serial': '8996609821111963708', 'device_serial': '1110336809', 'device': 'teltonika', 'user_id': '63e10486aab57a47992f24b5', 'created_by': '600fe9e50c847769bc3d0090', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2023-03-12 09:16:13', 'custom_fields': [], 'creator': 'rami.ahmed', 'company': '', 'owner': 'alajlan-sons-admin', 'last_update': {'dtt': 1714370217000, 'dts': 1714370220230, 'spd': 0, 'ang': 37, 'alt': 226, 'chPrams': {'workMode': {'v': 0, 'cdt': 1714369257000}, 'ePwrV': {'v': 12.892, 'cdt': 1714370217000}, 'parm24': {'v': 0, 'cdt': 1714369260000}, 'parm68': {'v': 0, 'cdt': 1713599447000}, 'ai1': {'v': 43, 'cdt': 1714369156000}, 'type': {'v': 6, 'cdt': 1712873978000}, 'di1': {'v': 0, 'cdt': 1714369257000}, 'result': {'v': '5665723a30332e32352e31355f3332204750533a41584e5f352e31305f333333332048773a464d42393230204d6f643a313320494d45493a33353430313731313935353536353020496e69743a323032342d322d352031393a313920557074696d653a36353331393335204d41433a303031453432443443384543205350433a312830292041584c3a31204f42443a3020424c3a312e372042543a34', 'cdt': 1713774660000}, 'protocol': {'v': 'FMB920', 'cdt': 1713774960000}, 'gpsStatus': {'v': 1, 'cdt': 1714368049000}, 'iPwrV': {'v': 3.92, 'cdt': 1714369317000}, 'parm250': {'v': 0, 'cdt': 1714369317000}, 'parm251': {'v': 0, 'cdt': 1714201811000}, 'event': {'v': 0, 'cdt': 1714369617000}, 'pdop': {'v': 0.5, 'cdt': 1714370217000}, 'Speed': {'v': 0, 'cdt': 1714369260000}, 'rssi': {'v': 3, 'cdt': 1714369617000}, 'motion': {'v': False, 'cdt': 1714369257000}, 'odometer': {'v': 96877985, 'cdt': 1714369257000}, 'parm14': {'v': 1119637082, 'cdt': 1712345538000}, 'sat': {'v': 12, 'cdt': 1714370217000}, 'parm11': {'v': 8996609821, 'cdt': 1712345538000}, 'priority': {'v': 0, 'cdt': 1714369317000}, 'hdop': {'v': 0.30000000000000004, 'cdt': 1714369260000}, 'parm247': {'v': 1, 'cdt': 1713984240091}, 'temp5': {'v': 0, 'cdt': 1712950461000}, 'tripOdometer': {'v': 0, 'cdt': 1714369617000}, 'parm200': {'v': 0, 'cdt': 1714367928000}}, 'prms': {'protocol': 'FMB920', 'priority': 0, 'sat': 12, 'event': 0, 'di1': 0, 'motion': 0, 'workMode': 0, 'rssi': 3, 'parm200': 0, 'gpsStatus': 1, 'pdop': 0.5, 'hdop': 0.30000000000000004, 'ePwrV': 12.892, 'Speed': 0, 'parm24': 0, 'iPwrV': 3.92, 'parm68': 0, 'ai1': 43, 'temp5': 0, 'tripOdometer': 0, 'odometer': 96877985, 'parm11': 8996609821, 'parm14': 1119637082}, 'devPrms': ['protocol', 'priority', 'sat', 'event', 'di1', 'motion', 'workMode', 'rssi', 'parm200', 'gpsStatus', 'pdop', 'hdop', 'ePwrV', 'Speed', 'parm24', 'iPwrV', 'parm68', 'ai1', 'temp5', 'tripOdometer', 'odometer', 'parm11', 'parm14'], 'old_params': {'pdop': 0.4, 'Speed': 0, 'rssi': 3, 'motion': 0, 'workMode': 0, 'odometer': 96877985, 'parm14': 1119637082, 'ePwrV': 12.893, 'parm24': 0, 'parm68': 0, 'sat': 14, 'parm11': 8996609821, 'ai1': 43, 'priority': 0, 'di1': 0, 'hdop': 0.30000000000000004, 'protocol': 'teltonika', 'temp5': 0, 'gpsStatus': 1, 'tripOdometer': 0, 'iPwrV': 3.92, 'event': 0, 'parm200': 0}, 'vLoc': 1, 'vCon': 1, 'ip': '37.216.100.203', 'rl': 0, 'trl': 39230.555, 'mdu': 0, 'tmdu': 2884967, 'eidl': 0, 'teidl': 485902, 'fc': 0, 'tfc': 4.048728, 'acc': 0, 'accOn': 3659741, 'accOff': 32887104, 'sdu': 300, 'tsdu': 957, 'lat': 21.3929, 'lng': 39.7189}, 'counters': {'odometer_type': 'gps', 'odometer': 39230.5573, 'engine_hours_type': 'acc', 'engine_hours': 3659741, 'last_acc': 0}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-04-29T06:02:17.264+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-29T06:02:17.314+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-29T06:02:17.361+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-29T06:02:17.390+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-29T06:02:17.444+0000] {_transport.py:335} INFO - GET https://dbelk1.afaqy.local:9200/_cluster/health [status:200 duration:0.082s]
[2024-04-29T06:02:18.136+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-29T06:02:20.461+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:2.342s]
[2024-04-29T06:02:20.748+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 112, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 3312 document(s) failed to index.
[2024-04-29T06:02:20.761+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=9, execution_date=20240429T054000, start_date=20240429T060154, end_date=20240429T060220
[2024-04-29T06:02:20.786+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22485 for task ETL_job (3312 document(s) failed to index.; 631811)
[2024-04-29T06:02:20.864+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-29T06:02:20.891+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
