[2024-05-06T22:01:53.970+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-06T21:40:00+00:00 map_index=5 [queued]>
[2024-05-06T22:01:53.987+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-06T21:40:00+00:00 map_index=5 [queued]>
[2024-05-06T22:01:53.988+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 4
[2024-05-06T22:01:54.007+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-06 21:40:00+00:00
[2024-05-06T22:01:54.014+0000] {standard_task_runner.py:60} INFO - Started process 817959 to run task
[2024-05-06T22:01:54.021+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-06T21:40:00+00:00', '--job-id', '36632', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpbsktf63i', '--map-index', '5']
[2024-05-06T22:01:54.023+0000] {standard_task_runner.py:88} INFO - Job 36632: Subtask ETL_job
[2024-05-06T22:01:54.107+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-06T21:40:00+00:00 map_index=5 [running]> on host a09da322e808
[2024-05-06T22:01:54.298+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T21:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-06T21:40:00+00:00'
[2024-05-06T22:01:54.300+0000] {Units_dag.py:99} INFO - i: 50000, chunk: 10000
[2024-05-06T22:01:54.300+0000] {Units_dag.py:100} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1MDMyODAzLCJleHAiOjE3MTc2MjQ4MDMsIm5iZiI6MTcxNTAzMjgwMywianRpIjoiakRUN0Vnamh3VTRCTmR6ZiIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.uD6Us0vcLu_IMVSKGbJFPtFUXR5xSr1Q4B6mTDers-8
[2024-05-06T22:02:10.510+0000] {Units_dag.py:104} INFO - {'_id': '62b054a622a4f81846551e2a', 'icon': 'icons/icon.png', 'driver_id': '64a3f4d17183b3751c4823ad', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '2793 - ا ر ه', 'operation_code': '', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': False, 'water': False}, 'imei': '860665057512955', 'sim_number': '+966830028522784', 'sim_serial': '8996609821110927851', 'device_serial': '860665057512955', 'device': 'bce', 'user_id': '5f8bf21303ed52b7fb1c11ba', 'created_by': '6062f4057f236761b5255ef4', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2022-06-20 14:06:14', 'custom_fields': [], 'creator': 'hassan.salem', 'company': '', 'owner': 'alwefaq-rent', 'last_update': {'dtt': 1715032902000, 'dts': 1715032913068, 'spd': 0, 'ang': 202, 'alt': 614, 'chPrams': {'ePwrV': {'v': 24.806, 'cdt': 1715032902000}, 'di16': {'v': 1, 'cdt': 1712752316000}, 'di15': {'v': 0, 'cdt': 1709662950000}, 'rssi1': {'v': 68, 'cdt': 1715032902000}, 'di14': {'v': 0, 'cdt': 1715030870000}, 'di13': {'v': 0, 'cdt': 1712752316000}, 'di12': {'v': 0, 'cdt': 1712752316000}, 'di11': {'v': 0, 'cdt': 1712752316000}, 'di10': {'v': 0, 'cdt': 1712752316000}, 'di2': {'v': 1, 'cdt': 1712490288000}, 'ai4': {'v': 16017, 'cdt': 1715032902000}, 'di1': {'v': 0, 'cdt': 1715030924000}, 'di4': {'v': 0, 'cdt': 1712752316000}, 'di3': {'v': 0, 'cdt': 1712752316000}, 'di6': {'v': 0, 'cdt': 1712752316000}, 'di5': {'v': 1, 'cdt': 1715031492000}, 'lac1': {'v': 4431, 'cdt': 1715019076000}, 'protocol': {'v': 'bce', 'cdt': 1712752316000}, 'di8': {'v': 1, 'cdt': 1712752316000}, 'di7': {'v': 0, 'cdt': 1715031252000}, 'di9': {'v': 0, 'cdt': 1712752316000}, 'iPwrV': {'v': 3.952, 'cdt': 1715032182000}, 'humidity': {'v': -1, 'cdt': 1712753516000}, 'cid1': {'v': 48231, 'cdt': 1715030844000}, 'temp': {'v': -273, 'cdt': 1712940706000}, 'odometer': {'v': 0, 'cdt': 1715030924000}, 'spd': {'v': 0, 'cdt': 1715030894000}, 'sat': {'v': 12, 'cdt': 1715030094000}, 'hdop': {'v': 1, 'cdt': 1714923334000}, 'ta': {'v': 0, 'cdt': 1712752316000}, 'mcc1': {'v': 420, 'cdt': 1713192290000}, 'mnc1': {'v': 3, 'cdt': 1713192290000}}, 'prms': {'protocol': 'bce', 'spd': 0, 'sat': 12, 'hdop': 1, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 0, 'di6': 0, 'di5': 1, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 0, 'ePwrV': 24.806, 'ai4': 16017, 'iPwrV': 3.952, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 4431, 'cid1': 48231, 'rssi1': 68, 'temp': -273, 'humidity': -1}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'ai4', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1', 'temp', 'humidity'], 'old_params': {'protocol': 'bce', 'spd': 0, 'sat': 12, 'hdop': 1, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 0, 'di6': 0, 'di5': 1, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 0, 'ePwrV': 24.815, 'ai4': 16120, 'iPwrV': 3.952, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 4431, 'cid1': 48231, 'rssi1': 69, 'temp': -273, 'humidity': -1}, 'vLoc': 1, 'vCon': 1, 'ip': '109.83.51.47', 'rl': 0, 'trl': 58679.5412, 'mdu': 0, 'tmdu': 3494936, 'eidl': 30, 'teidl': 13810274, 'fc': 0, 'tfc': 22.49712, 'acc': 1, 'accOn': 17640402, 'accOff': 42986120, 'sdu': 0, 'tsdu': 0, 'lat': 26.32554817199707, 'lng': 43.989864349365234}, 'counters': {'odometer_type': 'gps', 'odometer': 58848.5412, 'engine_hours_type': 'acc', 'engine_hours': 17640402, 'last_acc': 1}, 'is_wasl_connected': 'Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-06T22:02:11.184+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-06T22:02:11.242+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-06T22:02:11.334+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-06T22:02:11.362+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-06T22:02:11.439+0000] {_transport.py:335} INFO - GET https://dbelk2.afaqy.local:9200/_cluster/health [status:200 duration:0.103s]
[2024-05-06T22:02:12.012+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-06T22:02:12.153+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.158s]
[2024-05-06T22:02:12.416+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 112, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-06T22:02:12.430+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=5, execution_date=20240506T214000, start_date=20240506T220153, end_date=20240506T220212
[2024-05-06T22:02:12.450+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 36632 for task ETL_job (10000 document(s) failed to index.; 817959)
[2024-05-06T22:02:12.506+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-06T22:02:12.540+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
