[2024-05-08T06:23:15.641+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-08T06:00:00+00:00 map_index=2 [queued]>
[2024-05-08T06:23:15.661+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-08T06:00:00+00:00 map_index=2 [queued]>
[2024-05-08T06:23:15.661+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-05-08T06:23:15.679+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-08 06:00:00+00:00
[2024-05-08T06:23:15.686+0000] {standard_task_runner.py:60} INFO - Started process 854361 to run task
[2024-05-08T06:23:15.692+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-08T06:00:00+00:00', '--job-id', '40988', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpuidhzsml', '--map-index', '2']
[2024-05-08T06:23:15.694+0000] {standard_task_runner.py:88} INFO - Job 40988: Subtask ETL_job
[2024-05-08T06:23:15.785+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-08T06:00:00+00:00 map_index=2 [running]> on host a09da322e808
[2024-05-08T06:23:15.967+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-08T06:00:00+00:00'
[2024-05-08T06:23:15.968+0000] {Units_dag.py:98} INFO - i: 20000, chunk: 10000
[2024-05-08T06:23:15.969+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1MTQ5MjAzLCJleHAiOjE3MTc3NDEyMDMsIm5iZiI6MTcxNTE0OTIwMywianRpIjoiUVZRTHo4aTZxSGRwZTEwcCIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.c_YxHn5s0bW2tEVR5QCIY5Yi0nJ99-9kP7S4S7jzs44
[2024-05-08T06:23:32.815+0000] {Units_dag.py:103} INFO - {'_id': '618a70e9fabb56337f79c30f', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'weight', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': 'ب س م 7343', 'operation_code': '', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '862549044125154', 'sim_number': '+966862549084845', 'sim_serial': '862549044125154', 'device_serial': '862549044125154', 'device': 'ruptela', 'user_id': '5e539d8203ed52f71d634478', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2021-11-09 16:00:25', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'aemallamar', 'last_update': {'dtt': 1715149360000, 'dts': 1715149362010, 'spd': 0, 'ang': 58, 'alt': 650, 'chPrams': {'gsm': {'v': 13, 'cdt': 1715148986000}, 'io_1_176': {'v': 0, 'cdt': 1715144726000}, 'io_1_134': {'v': 0, 'cdt': 1715144655000}, 'io_1_136': {'v': 0, 'cdt': 1715086038000}, 'ai22': {'v': 2919, 'cdt': 1715149226000}, 'ePwrV': {'v': 25.067, 'cdt': 1715149360000}, 'io_1_135': {'v': 0, 'cdt': 1715144498000}, 'io_2_139': {'v': 14, 'cdt': 1715149360000}, 'di2': {'v': 0, 'cdt': 1636636963000}, 'operator': {'v': 42004, 'cdt': 1714544431000}, 'io_1_130': {'v': 0, 'cdt': 1715144834000}, 'di5': {'v': 1, 'cdt': 1715149360000}, 'io_2_131': {'v': 0, 'cdt': 1715001417000}, 'protocol': {'v': 'ruptela', 'cdt': 1714399624000}, 'io_2_137': {'v': 8, 'cdt': 1715149360000}, 'iPwrV': {'v': 4.081, 'cdt': 1715149360000}, 'event': {'v': 5, 'cdt': 1715149360000}, 'io_1_418': {'v': 1, 'cdt': 1714544431000}, 'move': {'v': 0, 'cdt': 1715144894000}, 'spd': {'v': 0, 'cdt': 1715144670000}, 'sat': {'v': 0, 'cdt': 1715149360000}, 'hdop': {'v': 0, 'cdt': 1715149360000}, 'io_2_560': {'v': 0, 'cdt': 1714472247000}, 'accTemp': {'v': 34, 'cdt': 1715146855000}, 'vOdometer': {'v': 188241213, 'cdt': 1715144786000}, 'io_1_405': {'v': 1, 'cdt': 1714399624000}}, 'prms': {'protocol': 'ruptela', 'sat': 0, 'spd': 0, 'hdop': 0, 'event': 5, 'io_1_130': 0, 'io_1_134': 0, 'io_1_135': 0, 'io_1_136': 0, 'di2': 0, 'di5': 1, 'accTemp': 34, 'io_1_405': 1, 'gsm': 13, 'move': 0, 'io_1_176': 0, 'io_1_418': 1, 'io_2_131': 0, 'io_2_137': 8, 'io_2_139': 14, 'ai22': 2919, 'io_2_560': 0, 'ePwrV': 25.067, 'iPwrV': 4.081, 'vOdometer': 188241213, 'operator': 42004}, 'devPrms': ['protocol', 'sat', 'spd', 'hdop', 'event', 'io_1_130', 'io_1_134', 'io_1_135', 'io_1_136', 'di2', 'di5', 'accTemp', 'io_1_405', 'gsm', 'move', 'io_1_176', 'io_1_418', 'io_2_131', 'io_2_137', 'io_2_139', 'ai22', 'io_2_560', 'ePwrV', 'iPwrV', 'vOdometer', 'operator'], 'old_params': {'protocol': 'ruptela', 'sat': 5, 'spd': 0, 'hdop': 1.3, 'event': 7, 'io_1_130': 0, 'io_1_134': 0, 'io_1_135': 0, 'io_1_136': 0, 'di2': 0, 'di5': 0, 'accTemp': 34, 'io_1_405': 1, 'gsm': 13, 'move': 0, 'io_1_176': 0, 'io_1_418': 1, 'io_2_131': 0, 'io_2_137': 60, 'io_2_139': 60, 'ai22': 2919, 'io_2_560': 0, 'ePwrV': 25.483, 'iPwrV': 4.082, 'vOdometer': 188241213, 'operator': 42004}, 'vLoc': 1, 'vCon': 0, 'ip': '51.39.13.86', 'rl': 0, 'trl': 189725.8343, 'mdu': 0, 'tmdu': 10368189, 'eidl': 0, 'teidl': 6646728, 'fc': 0, 'tfc': 681.609072, 'acc': 1, 'accOn': 143233480, 'accOff': 61795346, 'sdu': 14, 'tsdu': 2484, 'lat': 26.4323383, 'lng': 43.866495}, 'counters': {'odometer_type': 'gps', 'odometer': 189725.8343, 'engine_hours_type': 'acc', 'engine_hours': 143233480, 'last_acc': 1}, 'is_wasl_connected': 'Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-08T06:23:33.327+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-08T06:23:33.369+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-08T06:23:33.414+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-08T06:23:33.446+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-08T06:23:33.530+0000] {_transport.py:335} INFO - GET https://dbelk2.afaqy.local:9200/_cluster/health [status:200 duration:0.114s]
[2024-05-08T06:23:33.911+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-08T06:23:34.120+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.232s]
[2024-05-08T06:23:34.393+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-08T06:23:34.411+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=2, execution_date=20240508T060000, start_date=20240508T062315, end_date=20240508T062334
[2024-05-08T06:23:34.428+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 40988 for task ETL_job (10000 document(s) failed to index.; 854361)
[2024-05-08T06:23:34.485+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-08T06:23:34.519+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
