[2024-05-12T08:21:51.512+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T08:00:00+00:00 map_index=13 [queued]>
[2024-05-12T08:21:51.525+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T08:00:00+00:00 map_index=13 [queued]>
[2024-05-12T08:21:51.526+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 4
[2024-05-12T08:21:51.545+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-12 08:00:00+00:00
[2024-05-12T08:21:51.555+0000] {standard_task_runner.py:60} INFO - Started process 963312 to run task
[2024-05-12T08:21:51.568+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-12T08:00:00+00:00', '--job-id', '53581', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpctzs5ug4', '--map-index', '13']
[2024-05-12T08:21:51.570+0000] {standard_task_runner.py:88} INFO - Job 53581: Subtask ETL_job
[2024-05-12T08:21:51.659+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T08:00:00+00:00 map_index=13 [running]> on host a09da322e808
[2024-05-12T08:21:51.834+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-12T08:00:00+00:00'
[2024-05-12T08:21:51.837+0000] {Units_dag.py:98} INFO - i: 130000, chunk: 10000
[2024-05-12T08:21:51.838+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1NTAyMDA0LCJleHAiOjE3MTgwOTQwMDQsIm5iZiI6MTcxNTUwMjAwNCwianRpIjoiOFZoMzhjZ2RHaHp5aUp5ViIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.z-RD405Hb0ycQM874sWCeHPljUtTx9M4pn1Rj7-hhGM
[2024-05-12T08:22:22.494+0000] {Units_dag.py:103} INFO - {'_id': '65118e18a92b5e2b993de5e0', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'shipment_info': {'product_category': None, 'truck_type': None, 'shipment_type': None, 'shipment_payment_type': None, 'transporter_type': None, 'operating_area': None, 'weight_kilograms_per_day': None, 'kms_per_day': None, 'shipment_trip_drive_hrs_day': None, 'allowable_delay_drive_hrs_day': None, 'expected_shipment_trip_day': None, 'car_pay_per_day': None, 'exceeding_temperature_limit_per_day': None, 'temperature_upper_limit': None, 'exceeding_humidity_limit_per_day': None, 'humidity_upper_limit': None}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'name': 'LEFADDE13PTP06925', 'operation_code': '', 'device_gateway': '', 'skip_sim_information': False, 'imei': '863051060659835', 'sim_number': '+966830031851305', 'sim_serial': '421296753425', 'device_serial': '863051060659835', 'device': 'bce', 'user_id': '61c43b241b5e6d541b2b65ce', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2023-09-25 16:41:44', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'al-jabr-renta-admin', 'last_update': {'dtt': 1715502094000, 'dts': 1715502119492, 'spd': 0, 'ang': 164, 'alt': 32, 'chPrams': {'ePwrV': {'v': 13.897, 'cdt': 1715502094000}, 'di16': {'v': 1, 'cdt': 1713873652000}, 'di15': {'v': 0, 'cdt': 1693305524000}, 'rssi1': {'v': 96, 'cdt': 1715502092000}, 'di14': {'v': 0, 'cdt': 1715497836000}, 'di13': {'v': 0, 'cdt': 1714045054000}, 'di12': {'v': 0, 'cdt': 1714045054000}, 'di11': {'v': 0, 'cdt': 1714045054000}, 'di10': {'v': 0, 'cdt': 1693305524000}, 'di2': {'v': 1, 'cdt': 1713872706000}, 'di1': {'v': 1, 'cdt': 1715500592000}, 'di4': {'v': 0, 'cdt': 1714045054000}, 'di3': {'v': 0, 'cdt': 1714045054000}, 'di6': {'v': 1, 'cdt': 1714045054000}, 'di5': {'v': 1, 'cdt': 1715491302000}, 'lac1': {'v': 30105, 'cdt': 1715497808000}, 'protocol': {'v': 'bce', 'cdt': 1714045054000}, 'di8': {'v': 1, 'cdt': 1714045054000}, 'di7': {'v': 1, 'cdt': 1715491302000}, 'di9': {'v': 0, 'cdt': 1714045054000}, 'iPwrV': {'v': 4.042, 'cdt': 1715502094000}, 'cid1': {'v': 12551, 'cdt': 1715501702000}, 'odometer': {'v': 0, 'cdt': 1715499244000}, 'spd': {'v': 0, 'cdt': 1715502094000}, 'sat': {'v': 15, 'cdt': 1715501882000}, 'hdop': {'v': 1, 'cdt': 1715491422000}, 'ta': {'v': 0, 'cdt': 1714045354000}, 'mcc1': {'v': 420, 'cdt': 1714052980000}, 'mnc1': {'v': 4, 'cdt': 1715497808000}}, 'prms': {'protocol': 'bce', 'spd': 0, 'sat': 15, 'hdop': 1, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 1, 'di6': 1, 'di5': 1, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 1, 'ePwrV': 13.897, 'iPwrV': 4.042, 'ta': 0, 'mcc1': 420, 'mnc1': 4, 'lac1': 30105, 'cid1': 12551, 'rssi1': 96}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1'], 'old_params': {'protocol': 'bce', 'spd': 1, 'sat': 15, 'hdop': 1, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 1, 'di6': 1, 'di5': 1, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 1, 'ePwrV': 13.888, 'iPwrV': 4.044, 'ta': 0, 'mcc1': 420, 'mnc1': 4, 'lac1': 30105, 'cid1': 12551, 'rssi1': 96}, 'vLoc': 1, 'vCon': 1, 'ip': '51.39.12.53', 'rl': 0.0006, 'trl': 19984.2533, 'mdu': 0, 'tmdu': 1058664, 'eidl': 2, 'teidl': 609378, 'fc': 7.2e-05, 'tfc': 1.30728, 'acc': 1, 'accOn': 4286884, 'accOff': 18578174, 'sdu': 0, 'tsdu': 0, 'lat': 28.19977569580078, 'lng': 35.089263916015625}, 'counters': {'odometer_type': '', 'odometer': 19984.2452, 'engine_hours_type': '', 'engine_hours': 4286884, 'last_acc': 1}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-12T08:22:22.892+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T08:22:22.925+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T08:22:22.957+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T08:22:22.978+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:22:23.167+0000] {_transport.py:335} INFO - GET https://dbelk3.afaqy.local:9200/_cluster/health [status:200 duration:0.208s]
[2024-05-12T08:22:23.526+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:22:23.538+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.030s]
[2024-05-12T08:22:23.539+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk2.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-12T08:22:23.539+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-12T08:22:23.540+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:22:23.551+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.011s]
[2024-05-12T08:22:23.551+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk3.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-12T08:22:23.552+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 1 of 3)
[2024-05-12T08:22:23.573+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:22:23.725+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.173s]
[2024-05-12T08:22:24.044+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-12T08:22:24.062+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=13, execution_date=20240512T080000, start_date=20240512T082151, end_date=20240512T082224
[2024-05-12T08:22:24.079+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 53581 for task ETL_job (10000 document(s) failed to index.; 963312)
[2024-05-12T08:22:24.155+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-12T08:22:24.193+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
