[2024-05-12T08:01:53.390+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T07:40:00+00:00 map_index=2 [queued]>
[2024-05-12T08:01:53.431+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T07:40:00+00:00 map_index=2 [queued]>
[2024-05-12T08:01:53.432+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 4
[2024-05-12T08:01:53.453+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-12 07:40:00+00:00
[2024-05-12T08:01:53.462+0000] {standard_task_runner.py:60} INFO - Started process 962926 to run task
[2024-05-12T08:01:53.476+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-12T07:40:00+00:00', '--job-id', '53527', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp4m_z4oe2', '--map-index', '2']
[2024-05-12T08:01:53.478+0000] {standard_task_runner.py:88} INFO - Job 53527: Subtask ETL_job
[2024-05-12T08:01:53.620+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T07:40:00+00:00 map_index=2 [running]> on host a09da322e808
[2024-05-12T08:01:53.935+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T07:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-12T07:40:00+00:00'
[2024-05-12T08:01:53.936+0000] {Units_dag.py:98} INFO - i: 20000, chunk: 10000
[2024-05-12T08:01:53.936+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1NTAwODA0LCJleHAiOjE3MTgwOTI4MDQsIm5iZiI6MTcxNTUwMDgwNCwianRpIjoidlR6a1FSaEpwakgwRG02ciIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.vq3d2BTkxMJIh5ziQneZBO3fVC3uiD8DjKINBVKE9qo
[2024-05-12T08:02:15.606+0000] {Units_dag.py:103} INFO - {'_id': '618a70ef722bb208240a9359', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'weight', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': 'أ س أ 6548 -- 29-371', 'operation_code': '', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '862549043173791', 'sim_number': '+966862549465295', 'sim_serial': '862549043173791', 'device_serial': '862549043173791', 'device': 'ruptela', 'user_id': '5e539d8203ed52f71d634478', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2021-11-09 16:00:31', 'shipment_info': {'product_category': None, 'truck_type': None, 'shipment_type': None, 'shipment_payment_type': None, 'transporter_type': None, 'operating_area': None, 'weight_kilograms_per_day': None, 'kms_per_day': None, 'shipment_trip_drive_hrs_day': None, 'allowable_delay_drive_hrs_day': None, 'expected_shipment_trip_day': None, 'car_pay_per_day': None, 'exceeding_temperature_limit_per_day': None, 'temperature_upper_limit': None, 'exceeding_humidity_limit_per_day': None, 'humidity_upper_limit': None}, 'skip_sim_information': '', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'aemallamar', 'last_update': {'dtt': 1715500905000, 'dts': 1715500908158, 'spd': 9, 'ang': 359, 'alt': 870, 'chPrams': {'gsm': {'v': 15, 'cdt': 1715500891000}, 'io_1_176': {'v': 11, 'cdt': 1715500905000}, 'io_1_134': {'v': 0, 'cdt': 1715500905000}, 'io_1_136': {'v': 0, 'cdt': 1715500632000}, 'io_1_135': {'v': 0, 'cdt': 1715500898000}, 'ai22': {'v': 82, 'cdt': 1715500902000}, 'ePwrV': {'v': 28.319, 'cdt': 1715500905000}, 'io_2_139': {'v': 3, 'cdt': 1715500905000}, 'di2': {'v': 0, 'cdt': 1636784277000}, 'io_1_130': {'v': 15, 'cdt': 1715500905000}, 'operator': {'v': 42004, 'cdt': 1715483417000}, 'di5': {'v': 1, 'cdt': 1715497339000}, 'io_2_131': {'v': 0, 'cdt': 1714791947000}, 'protocol': {'v': 'ruptela', 'cdt': 1714636984000}, 'io_2_137': {'v': 0, 'cdt': 1715497458000}, 'iPwrV': {'v': 4.081, 'cdt': 1715500905000}, 'event': {'v': 9, 'cdt': 1715500730000}, 'io_1_418': {'v': 1, 'cdt': 1715483417000}, 'move': {'v': 1, 'cdt': 1715500265000}, 'spd': {'v': 9, 'cdt': 1715500905000}, 'sat': {'v': 19, 'cdt': 1715500891000}, 'hdop': {'v': 0.6, 'cdt': 1715498944000}, 'io_2_560': {'v': 0, 'cdt': 1713069290000}, 'accTemp': {'v': 49, 'cdt': 1715497449000}, 'vOdometer': {'v': 79975018, 'cdt': 1715500905000}, 'io_1_405': {'v': 1, 'cdt': 1714636984000}}, 'prms': {'protocol': 'ruptela', 'sat': 19, 'spd': 9, 'hdop': 0.6, 'event': 9, 'io_1_130': 15, 'io_1_134': 0, 'io_1_135': 0, 'io_1_136': 0, 'di2': 0, 'di5': 1, 'accTemp': 49, 'io_1_405': 1, 'gsm': 15, 'move': 1, 'io_1_176': 11, 'io_1_418': 1, 'io_2_131': 0, 'io_2_137': 0, 'io_2_139': 3, 'ai22': 82, 'io_2_560': 0, 'ePwrV': 28.319, 'iPwrV': 4.081, 'vOdometer': 79975018, 'operator': 42004}, 'devPrms': ['protocol', 'sat', 'spd', 'hdop', 'event', 'io_1_130', 'io_1_134', 'io_1_135', 'io_1_136', 'di2', 'di5', 'accTemp', 'io_1_405', 'gsm', 'move', 'io_1_176', 'io_1_418', 'io_2_131', 'io_2_137', 'io_2_139', 'ai22', 'io_2_560', 'ePwrV', 'iPwrV', 'vOdometer', 'operator'], 'old_params': {'protocol': 'ruptela', 'sat': 19, 'spd': 15, 'hdop': 0.6, 'event': 9, 'io_1_130': 20, 'io_1_134': 1, 'io_1_135': 0, 'io_1_136': 0, 'di2': 0, 'di5': 1, 'accTemp': 49, 'io_1_405': 1, 'gsm': 15, 'move': 1, 'io_1_176': 17, 'io_1_418': 1, 'io_2_131': 0, 'io_2_137': 0, 'io_2_139': 4, 'ai22': 82, 'io_2_560': 0, 'ePwrV': 28.349, 'iPwrV': 4.083, 'vOdometer': 79975007, 'operator': 42004}, 'vLoc': 1, 'vCon': 1, 'ip': '51.39.15.148', 'rl': 0.0116, 'trl': 81748.3469, 'mdu': 3, 'tmdu': 8290878, 'eidl': 0, 'teidl': 11744510, 'fc': 0.001392, 'tfc': 386.000268, 'acc': 1, 'accOn': 28349328, 'accOff': 50636132, 'sdu': 0, 'tsdu': 0, 'lat': 24.6762266, 'lng': 40.172185}, 'counters': {'odometer_type': 'gps', 'odometer': 81748.3538, 'engine_hours_type': 'acc', 'engine_hours': 28349328, 'last_acc': 1}, 'is_wasl_connected': 'Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-12T08:02:16.593+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T08:02:16.695+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T08:02:16.795+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T08:02:16.837+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:02:16.899+0000] {_transport.py:335} INFO - GET https://dbelk1.afaqy.local:9200/_cluster/health [status:200 duration:0.102s]
[2024-05-12T08:02:17.581+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:02:17.599+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.043s]
[2024-05-12T08:02:17.600+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk2.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-12T08:02:17.600+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-12T08:02:17.600+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:02:17.766+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.166s]
[2024-05-12T08:02:18.394+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-12T08:02:18.407+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=2, execution_date=20240512T074000, start_date=20240512T080153, end_date=20240512T080218
[2024-05-12T08:02:18.427+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 53527 for task ETL_job (10000 document(s) failed to index.; 962926)
[2024-05-12T08:02:18.504+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-12T08:02:18.532+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
