[2024-04-28T18:00:17.066+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-28T17:40:00+00:00 map_index=6 [queued]>
[2024-04-28T18:00:17.166+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-28T17:40:00+00:00 map_index=6 [queued]>
[2024-04-28T18:00:17.167+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-28T18:00:17.248+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-28 17:40:00+00:00
[2024-04-28T18:00:17.278+0000] {standard_task_runner.py:60} INFO - Started process 619801 to run task
[2024-04-28T18:00:17.348+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-04-28T17:40:00+00:00', '--job-id', '21612', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp9pewkqzn', '--map-index', '6']
[2024-04-28T18:00:17.369+0000] {standard_task_runner.py:88} INFO - Job 21612: Subtask ETL_job
[2024-04-28T18:00:17.607+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-28T17:40:00+00:00 map_index=6 [running]> on host a09da322e808
[2024-04-28T18:00:18.070+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T17:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T17:40:00+00:00'
[2024-04-28T18:00:18.073+0000] {Units_dag.py:99} INFO - i: 60000, chunk: 10000
[2024-04-28T18:00:18.073+0000] {Units_dag.py:100} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE0MzI3MjA0LCJleHAiOjE3MTY5MTkyMDQsIm5iZiI6MTcxNDMyNzIwNCwianRpIjoiVEtMVER0eXZBVWFTVkNEeCIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.bU2ETTOxuzyeLXiR3_GHnQizq-ZIRSX3AJ62IA58YHI
[2024-04-28T18:00:39.753+0000] {Units_dag.py:104} INFO - {'_id': '632884b20aa8e6364e77a5fa', 'icon': 'icons/D_7.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': None, 'measurement_type': 'count', 'max_capacity': 0, 'vin': None, 'plate_number': None, 'start_operation': None, 'contract_milage': None, 'opening_milage': None, 'model': None, 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '6583 - R S A', 'operation_code': '', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '357073298711348', 'sim_number': '+966830028793588', 'sim_serial': '996609821111336394', 'device_serial': '1124887022', 'device': 'teltonika', 'user_id': '62b9a1516bfc54699f7b0c2b', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2022-09-19 18:03:14', 'skip_sim_information': '', 'shipment_info': None, 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'saudi-hemaya-admin', 'last_update': {'dtt': 1714327206000, 'dts': 1714327209326, 'spd': 59, 'ang': 227, 'alt': 485, 'chPrams': {'Speed': {'v': 59, 'cdt': 1714327206000}, 'output1': {'v': False, 'cdt': 1713585467000}, 'output2': {'v': False, 'cdt': 1713585467000}, 'ePwrV': {'v': 29.117, 'cdt': 1714327206000}, 'parm24': {'v': 59, 'cdt': 1714327206000}, 'sat': {'v': 16, 'cdt': 1714327206000}, 'ai1': {'v': 14163, 'cdt': 1714327206000}, 'type': {'v': 6, 'cdt': 1712021671000}, 'priority': {'v': 0, 'cdt': 1713130912000}, 'di2': {'v': 0, 'cdt': 1713157387000}, 'di1': {'v': 1, 'cdt': 1714279084000}, 'result': {'v': '5665723a30332e32372e30375f3030204750533a41584e5f352e312e392048773a464d42313230204d6f643a333320494d45493a33353730373332393837313133343820496e69743a323032342d342d323820343a313720557074696d653a3436303434204d41433a303031453432374635373932205350433a312830292041584c3a32204f42443a3020424c3a312e31302042543a34', 'cdt': 1714323335000}, 'protocol': {'v': 'FMB120', 'cdt': 1714323365000}, 'parm6': {'v': 0, 'cdt': 1714162344000}, 'iPwrV': {'v': 4.0520000000000005, 'cdt': 1714326801000}, 'event': {'v': 0, 'cdt': 1713130912000}}, 'prms': {'protocol': 'FMB120', 'priority': 0, 'sat': 16, 'event': 0, 'di1': 1, 'output1': 0, 'di2': 0, 'output2': 0, 'ePwrV': 29.117, 'Speed': 59, 'parm24': 59, 'iPwrV': 4.0520000000000005, 'ai1': 14163, 'parm6': 0}, 'devPrms': ['protocol', 'priority', 'sat', 'event', 'di1', 'output1', 'di2', 'output2', 'ePwrV', 'Speed', 'parm24', 'iPwrV', 'ai1', 'parm6', 'type', 'result'], 'old_params': {'protocol': 'FMB120', 'priority': 0, 'sat': 17, 'event': 0, 'di1': 1, 'output1': 0, 'di2': 0, 'output2': 0, 'ePwrV': 29.048000000000002, 'Speed': 58, 'parm24': 58, 'iPwrV': 4.0520000000000005, 'ai1': 14164, 'parm6': 0}, 'vLoc': 1, 'vCon': 1, 'ip': '37.216.115.182', 'rl': 0.4848, 'trl': 113380.3715, 'mdu': 30, 'tmdu': 7258717, 'eidl': 0, 'teidl': 9330514, 'fc': 0.058176, 'tfc': 457.217412, 'acc': 1, 'accOn': 42400038, 'accOff': 1818463369, 'sdu': 0, 'tsdu': 0, 'lat': 25.3552616, 'lng': 47.8913166}, 'counters': {'odometer_type': 'gps', 'odometer': 113380.379, 'engine_hours_type': 'acc', 'engine_hours': 42400038, 'last_acc': 1}, 'is_wasl_connected': 'Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/D_7.png', 'hasCCTV': False}
[2024-04-28T18:00:40.584+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-28T18:00:40.630+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-28T18:00:40.681+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-28T18:00:40.700+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-28T18:00:40.769+0000] {_transport.py:335} INFO - GET https://dbelk3.afaqy.local:9200/_cluster/health [status:200 duration:0.086s]
[2024-04-28T18:00:41.284+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-28T18:00:44.602+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:3.352s]
[2024-04-28T18:00:45.169+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 112, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 2048 document(s) failed to index.
[2024-04-28T18:00:45.191+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=6, execution_date=20240428T174000, start_date=20240428T180017, end_date=20240428T180045
[2024-04-28T18:00:46.124+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21612 for task ETL_job (2048 document(s) failed to index.; 619801)
[2024-04-28T18:00:46.293+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-28T18:00:46.391+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
