[2024-05-12T05:45:43.807+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T05:20:00+00:00 map_index=3 [queued]>
[2024-05-12T05:45:43.822+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T05:20:00+00:00 map_index=3 [queued]>
[2024-05-12T05:45:43.822+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-05-12T05:45:43.843+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-12 05:20:00+00:00
[2024-05-12T05:45:43.850+0000] {standard_task_runner.py:60} INFO - Started process 960059 to run task
[2024-05-12T05:45:43.862+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-12T05:20:00+00:00', '--job-id', '53074', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp57d_yf54', '--map-index', '3']
[2024-05-12T05:45:43.864+0000] {standard_task_runner.py:88} INFO - Job 53074: Subtask ETL_job
[2024-05-12T05:45:43.976+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T05:20:00+00:00 map_index=3 [running]> on host a09da322e808
[2024-05-12T05:45:44.151+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T05:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-12T05:20:00+00:00'
[2024-05-12T05:45:44.152+0000] {Units_dag.py:98} INFO - i: 30000, chunk: 10000
[2024-05-12T05:45:44.153+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1NDkyNDA0LCJleHAiOjE3MTgwODQ0MDQsIm5iZiI6MTcxNTQ5MjQwNCwianRpIjoiU29PY0diOGg2UGFEbFI1ZSIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.zsewfPvVi-pMKyh-yfrfOtgbsg0HSfPLWrCGrQ-Qx_0
[2024-05-12T05:46:03.433+0000] {Units_dag.py:103} INFO - {'_id': '62173fe490676a34b337c191', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': 'PEUGEOT PARTNER SHORT CARGO1.6', 'measurement_type': 'count', 'max_capacity': 0, 'vin': 'VR3EF9HPANJ524083', 'plate_number': 'ب س ن 3829', 'start_operation': None, 'contract_milage': None, 'opening_milage': None, 'model': '2022', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': 'VR3EF9HPANJ524083', 'operation_code': '3829 NSB', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '866854051783275', 'sim_number': '+966830020805688', 'sim_serial': '996609821110853426', 'device_serial': '866854051783275', 'device': 'bce', 'user_id': '61c43b241b5e6d541b2b65ce', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2022-02-24 11:20:52', 'shipment_info': None, 'skip_sim_information': False, 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'al-jabr-renta-admin', 'last_update': {'dtt': 1715492732000, 'dts': 1715492741827, 'spd': 23, 'ang': 198, 'alt': 4, 'chPrams': {'ePwrV': {'v': 13.915, 'cdt': 1715492732000}, 'di16': {'v': 0, 'cdt': 1715492726000}, 'rssi1': {'v': 63, 'cdt': 1715492732000}, 'di15': {'v': 0, 'cdt': 1687173760000}, 'di14': {'v': 0, 'cdt': 1715492618000}, 'di13': {'v': 0, 'cdt': 1713095264000}, 'di12': {'v': 0, 'cdt': 1713095264000}, 'di11': {'v': 0, 'cdt': 1713095264000}, 'di10': {'v': 0, 'cdt': 1645700544000}, 'di2': {'v': 1, 'cdt': 1714290694000}, 'di1': {'v': 1, 'cdt': 1715492458000}, 'di4': {'v': 0, 'cdt': 1713095264000}, 'di3': {'v': 0, 'cdt': 1713095264000}, 'di6': {'v': 1, 'cdt': 1713095264000}, 'di5': {'v': 1, 'cdt': 1715492458000}, 'lac1': {'v': 3601, 'cdt': 1715492712000}, 'protocol': {'v': 'bce', 'cdt': 1713095264000}, 'di8': {'v': 1, 'cdt': 1713095264000}, 'di7': {'v': 1, 'cdt': 1715492458000}, 'di9': {'v': 0, 'cdt': 1713095264000}, 'iPwrV': {'v': 4.128, 'cdt': 1715492576000}, 'cid1': {'v': 30953, 'cdt': 1715492732000}, 'odometer': {'v': 1110581192, 'cdt': 1715492732000}, 'spd': {'v': 23, 'cdt': 1715492732000}, 'sat': {'v': 15, 'cdt': 1715492532000}, 'hdop': {'v': 1, 'cdt': 1715433304000}, 'ta': {'v': 0, 'cdt': 1713095264000}, 'mcc1': {'v': 420, 'cdt': 1714003958000}, 'mnc1': {'v': 3, 'cdt': 1714003958000}}, 'prms': {'protocol': 'bce', 'spd': 23, 'sat': 15, 'hdop': 1, 'odometer': 1110581192, 'di16': 0, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 1, 'di6': 1, 'di5': 1, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 1, 'ePwrV': 13.915, 'iPwrV': 4.128, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 3601, 'cid1': 30953, 'rssi1': 63}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1'], 'old_params': {'protocol': 'bce', 'spd': 47, 'sat': 15, 'hdop': 1, 'odometer': 1130244234, 'di16': 0, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 1, 'di6': 1, 'di5': 1, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 1, 'ePwrV': 13.826, 'iPwrV': 4.128, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 3601, 'cid1': 30951, 'rssi1': 44}, 'vLoc': 1, 'vCon': 1, 'ip': '109.83.12.216', 'rl': 0.044, 'trl': 114317.1245, 'mdu': 6, 'tmdu': 8535816, 'eidl': 0, 'teidl': 7082010, 'fc': 0.00528, 'tfc': 26.285688, 'acc': 1, 'accOn': 5955056, 'accOff': 57964232, 'sdu': 0, 'tsdu': 0, 'lat': 26.453826904296875, 'lng': 50.06228256225586}, 'counters': {'odometer_type': 'gps', 'odometer': 114330.1205, 'engine_hours_type': 'acc', 'engine_hours': 5955056, 'last_acc': 1}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-12T05:46:03.962+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T05:46:04.044+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T05:46:04.093+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T05:46:04.114+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T05:46:04.196+0000] {_transport.py:335} INFO - GET https://dbelk2.afaqy.local:9200/_cluster/health [status:200 duration:0.101s]
[2024-05-12T05:46:04.579+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T05:46:04.773+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.212s]
[2024-05-12T05:46:05.060+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-12T05:46:05.078+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=3, execution_date=20240512T052000, start_date=20240512T054543, end_date=20240512T054605
[2024-05-12T05:46:05.101+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 53074 for task ETL_job (10000 document(s) failed to index.; 960059)
[2024-05-12T05:46:05.161+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-12T05:46:05.196+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
