[2024-05-09T08:21:53.273+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-09T08:00:00+00:00 map_index=5 [queued]>
[2024-05-09T08:21:53.286+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-09T08:00:00+00:00 map_index=5 [queued]>
[2024-05-09T08:21:53.287+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 4
[2024-05-09T08:21:53.304+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-09 08:00:00+00:00
[2024-05-09T08:21:53.311+0000] {standard_task_runner.py:60} INFO - Started process 882185 to run task
[2024-05-09T08:21:53.319+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-09T08:00:00+00:00', '--job-id', '43797', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp5worgrp1', '--map-index', '5']
[2024-05-09T08:21:53.325+0000] {standard_task_runner.py:88} INFO - Job 43797: Subtask ETL_job
[2024-05-09T08:21:53.404+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-09T08:00:00+00:00 map_index=5 [running]> on host a09da322e808
[2024-05-09T08:21:53.567+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T08:00:00+00:00'
[2024-05-09T08:21:53.568+0000] {Units_dag.py:98} INFO - i: 50000, chunk: 10000
[2024-05-09T08:21:53.568+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1MjQyODA0LCJleHAiOjE3MTc4MzQ4MDQsIm5iZiI6MTcxNTI0MjgwNCwianRpIjoidWRZdEtncVpaQ0F6OUxXOCIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.d4Cl7wKGKhb5tjbtDIs61zYUYp90KLPZ77Xw6aqPT8k
[2024-05-09T08:22:12.390+0000] {Units_dag.py:103} INFO - {'_id': '62b078846eb1173cc458d078', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'measurement_type': 'count', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '722 - V U H', 'operation_code': None, 'device_gateway': None, 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '866854051810995', 'sim_number': '+966830028856816', 'sim_serial': '996609821111313315', 'device_serial': '866854051810995', 'device': 'bce', 'user_id': '62693bbb07a96a0b2714bff8', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2022-06-20 16:39:16', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'hawadij-rental-admin', 'last_update': {'dtt': 1715242556000, 'dts': 1715242664255, 'spd': 0, 'ang': 52, 'alt': 613, 'chPrams': {'ePwrV': {'v': 12.355, 'cdt': 1715242556000}, 'di16': {'v': 1, 'cdt': 1712916060000}, 'rssi1': {'v': 61, 'cdt': 1715236550000}, 'di15': {'v': 0, 'cdt': 1714437750000}, 'di14': {'v': 0, 'cdt': 1715108940000}, 'di13': {'v': 0, 'cdt': 1712916060000}, 'di12': {'v': 0, 'cdt': 1714437750000}, 'di11': {'v': 0, 'cdt': 1714437750000}, 'di10': {'v': 0, 'cdt': 1714437750000}, 'di2': {'v': 1, 'cdt': 1714531176000}, 'di1': {'v': 0, 'cdt': 1715201404000}, 'di4': {'v': 0, 'cdt': 1714437750000}, 'di3': {'v': 0, 'cdt': 1714437750000}, 'di6': {'v': 1, 'cdt': 1714437750000}, 'di5': {'v': 0, 'cdt': 1715201404000}, 'lac1': {'v': 1252, 'cdt': 1715020068000}, 'protocol': {'v': 'bce', 'cdt': 1714437750000}, 'di8': {'v': 1, 'cdt': 1714437750000}, 'di7': {'v': 0, 'cdt': 1715201404000}, 'di9': {'v': 0, 'cdt': 1714437750000}, 'iPwrV': {'v': 4.092, 'cdt': 1715241956000}, 'cid1': {'v': 10673, 'cdt': 1715233244000}, 'odometer': {'v': 0, 'cdt': 1715201704000}, 'spd': {'v': 0, 'cdt': 1715201704000}, 'sat': {'v': 13, 'cdt': 1715241956000}, 'hdop': {'v': 1, 'cdt': 1715241656000}, 'ta': {'v': 0, 'cdt': 1714437750000}, 'mcc1': {'v': 420, 'cdt': 1714437750000}, 'mnc1': {'v': 3, 'cdt': 1714437750000}}, 'prms': {'protocol': 'bce', 'spd': 0, 'sat': 13, 'hdop': 1, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 0, 'di6': 1, 'di5': 0, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 0, 'ePwrV': 12.355, 'iPwrV': 4.092, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 1252, 'cid1': 10673, 'rssi1': 61}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1'], 'old_params': {'di16': 1, 'ePwrV': 12.319, 'di15': 0, 'rssi1': 61, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di2': 1, 'di1': 0, 'di4': 0, 'di3': 0, 'di6': 1, 'di5': 0, 'lac1': 1252, 'protocol': 'bce', 'di8': 1, 'di7': 0, 'di9': 0, 'iPwrV': 4.092, 'cid1': 10673, 'odometer': 0, 'spd': 0, 'sat': 13, 'hdop': 1, 'ta': 0, 'mcc1': 420, 'mnc1': 3}, 'vLoc': 1, 'vCon': 1, 'ip': '109.83.109.126', 'rl': 0, 'trl': 47788.3679, 'mdu': 0, 'tmdu': 2891660, 'eidl': 0, 'teidl': 1754734, 'fc': 0, 'tfc': 0.197424, 'acc': 0, 'accOn': 5270096, 'accOff': 57816644, 'sdu': 300, 'tsdu': 41152, 'lat': 24.614425659179688, 'lng': 46.725521087646484}, 'counters': {'odometer_type': 'gps', 'odometer': 47788.3679, 'engine_hours_type': 'acc', 'engine_hours': 5270096, 'last_acc': 0}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-09T08:22:13.010+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-09T08:22:13.065+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-09T08:22:13.115+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-09T08:22:13.136+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-09T08:22:13.219+0000] {_transport.py:335} INFO - GET https://dbelk3.afaqy.local:9200/_cluster/health [status:200 duration:0.101s]
[2024-05-09T08:22:14.043+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-09T08:22:14.056+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.044s]
[2024-05-09T08:22:14.057+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk2.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-09T08:22:14.057+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-09T08:22:14.058+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-09T08:22:14.284+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.226s]
[2024-05-09T08:22:15.105+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-09T08:22:15.127+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=5, execution_date=20240509T080000, start_date=20240509T082153, end_date=20240509T082215
[2024-05-09T08:22:15.143+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 43797 for task ETL_job (10000 document(s) failed to index.; 882185)
[2024-05-09T08:22:15.229+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-09T08:22:15.256+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
