[2024-05-10T22:21:50.651+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T22:00:00+00:00 map_index=5 [queued]>
[2024-05-10T22:21:50.670+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T22:00:00+00:00 map_index=5 [queued]>
[2024-05-10T22:21:50.670+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 4
[2024-05-10T22:21:50.692+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-10 22:00:00+00:00
[2024-05-10T22:21:50.703+0000] {standard_task_runner.py:60} INFO - Started process 924760 to run task
[2024-05-10T22:21:50.717+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-10T22:00:00+00:00', '--job-id', '48858', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpcl5472yx', '--map-index', '5']
[2024-05-10T22:21:50.722+0000] {standard_task_runner.py:88} INFO - Job 48858: Subtask ETL_job
[2024-05-10T22:21:50.829+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T22:00:00+00:00 map_index=5 [running]> on host a09da322e808
[2024-05-10T22:21:51.049+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T22:00:00+00:00'
[2024-05-10T22:21:51.051+0000] {Units_dag.py:98} INFO - i: 50000, chunk: 10000
[2024-05-10T22:21:51.052+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1Mzc5NjA0LCJleHAiOjE3MTc5NzE2MDQsIm5iZiI6MTcxNTM3OTYwNCwianRpIjoiNnlEeVZmbmVxU2NyVHIzTCIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.rPawu0dsZVE46Aom7RPyHLozfCwoAyXUYQ3AMe3rG94
[2024-05-10T22:22:07.605+0000] {Units_dag.py:103} INFO - {'_id': '62b07df45e94ae88895b6738', 'imei': '359633109980842', 'updated_at': '2024-04-18 11:18:59', 'custom_fields': [], 'creator': '', 'company': '', 'owner': '', 'last_update': {'dtt': 1655737890000, 'dts': 1655737893483, 'spd': 3, 'ang': 314, 'alt': 563, 'chPrams': {'pdop': {'v': 0.4, 'cdt': 1655737890000}, 'rssi': {'v': 3, 'cdt': 1655737817000}, 'motion': {'v': True, 'cdt': 1655735549000}, 'odometer': {'v': 89947337, 'cdt': 1655737890000}, 'ePwrV': {'v': 27.321, 'cdt': 1655737890000}, 'parm68': {'v': 0, 'cdt': 1654926904000}, 'sat': {'v': 17, 'cdt': 1655737889000}, 'ai1': {'v': 217, 'cdt': 1655688325000}, 'priority': {'v': 0, 'cdt': 1655703673000}, 'di1': {'v': 1, 'cdt': 1655703073000}, 'hdop': {'v': 0.30000000000000004, 'cdt': 1655736745000}, 'operator': {'v': 42003, 'cdt': 1654590409000}, 'protocol': {'v': 'teltonika_FMB640', 'cdt': 1654926904000}, 'gpsStatus': {'v': 1, 'cdt': 1654033021000}, 'iPwrV': {'v': 0, 'cdt': 1655737712000}, 'event': {'v': 0, 'cdt': 1655703673000}, 'parm200': {'v': 0, 'cdt': 1654926904000}}, 'prms': {'protocol': 'teltonika_FMB640', 'priority': 0, 'sat': 17, 'event': 0, 'di1': 1, 'motion': 1, 'rssi': 3, 'parm200': 0, 'gpsStatus': 1, 'pdop': 0.4, 'hdop': 0.30000000000000004, 'ePwrV': 27.321, 'iPwrV': 0, 'parm68': 0, 'ai1': 217, 'operator': 42003, 'odometer': 89947337}, 'devPrms': ['protocol', 'priority', 'sat', 'event', 'di1', 'motion', 'rssi', 'parm200', 'gpsStatus', 'pdop', 'hdop', 'ePwrV', 'iPwrV', 'parm68', 'ai1', 'operator', 'odometer'], 'old_params': {'protocol': 'teltonika_FMB640', 'priority': 0, 'sat': 17, 'event': 0, 'di1': 1, 'motion': 1, 'rssi': 3, 'parm200': 0, 'gpsStatus': 1, 'pdop': 0.6000000000000001, 'hdop': 0.30000000000000004, 'ePwrV': 27.303, 'iPwrV': 0, 'parm68': 0, 'ai1': 217, 'operator': 42003, 'odometer': 89947333}, 'vLoc': 1, 'vCon': 1, 'ip': '109.82.113.47', 'rl': 0.0032, 'trl': 90371.2694, 'mdu': 1, 'tmdu': 6809469, 'eidl': 0, 'teidl': 10564392, 'fc': 0.000384, 'tfc': 8.864496, 'acc': 1, 'accOn': 3215849510, 'accOff': 17801846, 'sdu': 0, 'tsdu': 0, 'lat': 24.6035866, 'lng': 46.908395}, 'counters': {'engine_hours': 3215849510, 'last_acc': 1, 'odometer': 90371.2743}, 'is_wasl_connected': 'Not Connected', 'iconUrl': '', 'hasCCTV': False}
[2024-05-10T22:22:08.161+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T22:22:08.205+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T22:22:08.254+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T22:22:08.277+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T22:22:08.383+0000] {_transport.py:335} INFO - GET https://dbelk3.afaqy.local:9200/_cluster/health [status:200 duration:0.127s]
[2024-05-10T22:22:08.754+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T22:22:08.767+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.031s]
[2024-05-10T22:22:08.768+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk2.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-10T22:22:08.768+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-10T22:22:08.769+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T22:22:08.780+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.011s]
[2024-05-10T22:22:08.780+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk3.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-10T22:22:08.781+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 1 of 3)
[2024-05-10T22:22:08.811+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T22:22:10.527+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:1.746s]
[2024-05-10T22:22:10.876+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-05-10T22:22:10.894+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=5, execution_date=20240510T220000, start_date=20240510T222150, end_date=20240510T222210
[2024-05-10T22:22:10.950+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-10T22:22:10.985+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
